language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-get install libltdl-dev libdb-dev zlib1g-dev libssl-dev

script: ./configure --with-bdb --disable-shared && make && make check
